# Generated by Django 5.0.3 on 2024-04-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='categorie_manga',
            field=models.CharField(default='Defaut', max_length=100),
        ),
        migrations.AddField(
            model_name='manga',
            name='type_manga',
            field=models.CharField(default='Defaut', max_length=100),
        ),
    ]
