# Generated by Django 5.0.3 on 2024-04-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_manga_vue_manga_favories_vue'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='genre_manga',
            field=models.CharField(default='Defaut', max_length=100),
        ),
        migrations.AddField(
            model_name='manga',
            name='langue_manga',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='manga',
            name='public_averti_manga',
            field=models.CharField(default='Defaut', max_length=100),
        ),
        migrations.AddField(
            model_name='manga',
            name='saison_manga',
            field=models.CharField(default='Defaut', max_length=100),
        ),
        migrations.AddField(
            model_name='manga',
            name='site_web_manga',
            field=models.CharField(default='Defaut', max_length=100),
        ),
        migrations.AddField(
            model_name='manga',
            name='theme_manga',
            field=models.CharField(default='Defaut', max_length=100),
        ),
    ]
