# Generated by Django 5.0.3 on 2024-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_manga_genre_manga_manga_langue_manga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='image_content_4',
            field=models.ImageField(default='', upload_to='manga_covers4/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image_content_1',
            field=models.ImageField(upload_to='manga_covers1/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image_content_2',
            field=models.ImageField(upload_to='manga_covers2/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image_content_3',
            field=models.ImageField(upload_to='manga_covers3/'),
        ),
    ]
