# Generated by Django 5.0.3 on 2024-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_manga_image_content_4_alter_manga_image_content_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='image_content_1',
            field=models.ImageField(null=True, upload_to='manga_covers/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image_content_2',
            field=models.ImageField(null=True, upload_to='manga_covers/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image_content_3',
            field=models.ImageField(null=True, upload_to='manga_covers/'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='image_content_4',
            field=models.ImageField(null=True, upload_to='manga_covers/'),
        ),
    ]
